# [tool.hatch...]

[env]
requires = [
  "hatch-pip-compile",
]

# [default.extra-scripts]
# pip = "{env:HATCH_UV} pip {args}"

[envs.default]
# installer = "uv"
type = "pip-compile"
pip-compile-resolver = "uv"
# lock-filename = "requirements.lock"
