# [tool.hatch...]

[env]
requires = [
  "hatch-pip-compile",
]

# [default.extra-scripts]
# pip = "{env:HATCH_UV} pip {args}"

[envs.default]
# installer = "uv"
type = "pip-compile"
pip-compile-resolver = "uv"
# lock-filename = "requirements.lock"

#----

[version]
path = "src/heiwa4126_hello_python/__about__.py"

[envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]

[envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/heiwa4126_hello_python tests}"

[envs.default.env-vars]
CIDFILE = ".heiwa4126-hello-python.cid"
IMGNAME = "heiwa4126-hello-python"
MODNAME = "heiwa4126_hello_python"

[envs.default.scripts]
main = "python src/heiwa4126_hello_python/__main__.py {args}"
ex1 = "python examples/ex1.py"

tag-it = [
  "git add --all",
  "git commit -am \"v$(hatch version)\"",
  "git tag -a \"v$(hatch version)\" -m \"v$(hatch version)\"",
]
bump = [
  "hatch version patch",
  "tag-it",
]
minor = [
  "hatch version minor",
  "tag-it",
]

"build-docker" = [
  "hatch build",
  """docker build . \\
  --build-arg BDIST="$MODNAME-$(hatch version)-py3-none-any.whl" \\
  -t $IMGNAME:$(hatch version)""",
  "docker tag $IMGNAME:$(hatch version) $IMGNAME:latest",
  "list-docker",
]
"list-docker" = "docker images $IMGNAME"
"start-docker" = "docker run --rm $IMGNAME:latest"

"trivy-check" = [
  "trivy config .",
  "trivy fs .",
]

"trivy-check-image" = "trivy image $IMGNAME:$(hatch version) --ignore-unfixed"
